version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:5.0.8-focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: clean-node-api
    image: node:12
    working_dir: /usr/src/clean-node-api
    restart: always
    command: sh -c "npm install --ignore-scripts && npm run dev"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    ports:
      - 5050:5050
      - 9222:9222
    volumes:
      - ./src/:/usr/src/clean-node-api/src/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./tsconfig.json:/usr/src/clean-node-api/tsconfig.json
    depends_on:
      - mongo